-- Construction Menu Map (Derived)
-- Generated: 2026-04-07 17:43:47
-- Source: all-optimized.json + AGS_CIV_PREFIXES
-- Usage: CONSTRUCTION_MENU_MAP[race_name] returns per-civ menu info

CONSTRUCTION_MENU_MAP = {
    ["abbasid"] = {
        prefix = "abb_",
        age_type = "wing",
        in_cardinal = true,
        age_menus = { "abb_age2", "abb_age3", "abb_age4" },
        wonder_menus = { "abb_age2_wonders" },
    },
    ["abbasid_ha_01"] = {
        prefix = "abb_ha_01_",
        age_type = "wing",
        in_cardinal = false,
        age_menus = { "abb_ha_01_age2", "abb_ha_01_age3", "abb_ha_01_age4" },
        wonder_menus = { "abb_ha_01_age2_wonders" },
    },
    ["byzantine"] = {
        prefix = "byz_",
        age_type = "landmark",
        in_cardinal = false,
        age_menus = { "byz_age2", "byz_age3", "byz_age4" },
        wonder_menus = { "byz_age1_wonders", "byz_age2_wonders", "byz_age3_wonders" },
    },
    ["byzantine_ha_mac"] = {
        prefix = "byz_ha_mac_",
        age_type = "landmark",
        in_cardinal = false,
        age_menus = { "byz_ha_mac_age2", "byz_ha_mac_age3", "byz_ha_mac_age4" },
        wonder_menus = { "byz_ha_mac_age1_wonders", "byz_ha_mac_age2_wonders", "byz_ha_mac_age3_wonders" },
    },
    ["chinese"] = {
        prefix = "chi_",
        age_type = "landmark",
        in_cardinal = true,
        age_menus = { "chi_age2", "chi_age3", "chi_age4" },
        wonder_menus = { "chi_age1_wonders", "chi_age2_wonders", "chi_age3_wonders" },
    },
    ["chinese_ha_01"] = {
        prefix = "chi_ha_01_",
        age_type = "landmark",
        in_cardinal = false,
        age_menus = { "chi_ha_01_age2", "chi_ha_01_age3", "chi_ha_01_age4" },
        wonder_menus = { "chi_ha_01_age1_wonders", "chi_ha_01_age2_wonders", "chi_ha_01_age3_wonders" },
    },
    ["english"] = {
        prefix = "eng_",
        age_type = "landmark",
        in_cardinal = true,
        age_menus = { "eng_age2", "eng_age3", "eng_age4" },
        wonder_menus = { "eng_age1_wonders", "eng_age2_wonders", "eng_age3_wonders" },
    },
    ["french"] = {
        prefix = "fre_",
        age_type = "landmark",
        in_cardinal = true,
        age_menus = { "fre_age2", "fre_age3", "fre_age4" },
        wonder_menus = { "fre_age1_wonders", "fre_age2_wonders", "fre_age3_wonders" },
    },
    ["french_ha_01"] = {
        prefix = "fre_ha_01_",
        age_type = "landmark",
        in_cardinal = false,
        age_menus = { "fre_ha_01_age2", "fre_ha_01_age3", "fre_ha_01_age4" },
        wonder_menus = { "fre_ha_01_age1_wonders", "fre_ha_01_age2_wonders", "fre_ha_01_age3_wonders" },
    },
    ["hre"] = {
        prefix = "hre_",
        age_type = "landmark",
        in_cardinal = true,
        age_menus = { "hre_age2", "hre_age3", "hre_age4" },
        wonder_menus = { "hre_age1_wonders", "hre_age2_wonders", "hre_age3_wonders" },
    },
    ["hre_ha_01"] = {
        prefix = "hre_ha_01_",
        age_type = "landmark",
        in_cardinal = false,
        age_menus = { "hre_ha_01_age2", "hre_ha_01_age3", "hre_ha_01_age4" },
        wonder_menus = { "hre_ha_01_age1_wonders", "hre_ha_01_age2_wonders", "hre_ha_01_age3_wonders" },
    },
    ["japanese"] = {
        prefix = "jpn_",
        age_type = "landmark",
        in_cardinal = false,
        age_menus = { "jpn_age2", "jpn_age3", "jpn_age4" },
        wonder_menus = { "jpn_age1_wonders", "jpn_age2_wonders", "jpn_age3_wonders" },
    },
    ["japanese_ha_sen"] = {
        prefix = "jpn_ha_sen_",
        age_type = "landmark",
        in_cardinal = false,
        age_menus = { "jpn_ha_sen_age2", "jpn_ha_sen_age3", "jpn_ha_sen_age4" },
        wonder_menus = { "jpn_ha_sen_age1_wonders", "jpn_ha_sen_age2_wonders", "jpn_ha_sen_age3_wonders" },
    },
    ["lancaster"] = {
        prefix = "lan_",
        age_type = "landmark",
        in_cardinal = false,
        age_menus = { "lan_age2", "lan_age3", "lan_age4" },
        wonder_menus = { "lan_age1_wonders", "lan_age2_wonders", "lan_age3_wonders" },
    },
    ["malian"] = {
        prefix = "mal_",
        age_type = "landmark",
        in_cardinal = false,
        age_menus = { "mal_age2", "mal_age3", "mal_age4" },
        wonder_menus = { "mal_age1_wonders", "mal_age2_wonders", "mal_age3_wonders" },
    },
    ["mongol"] = {
        prefix = "mon_",
        age_type = "landmark",
        in_cardinal = true,
        age_menus = { "mon_age2", "mon_age3", "mon_age4" },
        wonder_menus = { "mon_age1_wonders", "mon_age2_wonders", "mon_age3_wonders" },
    },
    ["mongol_ha_gol"] = {
        prefix = "mon_ha_gol_",
        age_type = "upgrade",
        in_cardinal = false,
        age_menus = { "mon_ha_gol_age2", "mon_ha_gol_age3", "mon_ha_gol_age4" },
        wonder_menus = { "mon_ha_gol_age1_wonders" },
    },
    ["ottoman"] = {
        prefix = "ott_",
        age_type = "landmark",
        in_cardinal = true,
        age_menus = { "ott_age2", "ott_age3", "ott_age4" },
        wonder_menus = { "ott_age1_wonders", "ott_age2_wonders", "ott_age3_wonders" },
    },
    ["rus"] = {
        prefix = "rus_",
        age_type = "landmark",
        in_cardinal = true,
        age_menus = { "rus_age2", "rus_age3", "rus_age4" },
        wonder_menus = { "rus_age1_wonders", "rus_age2_wonders", "rus_age3_wonders" },
    },
    ["sultanate"] = {
        prefix = "sul_",
        age_type = "landmark",
        in_cardinal = true,
        age_menus = { "sul_age2", "sul_age3", "sul_age4" },
        wonder_menus = { "sul_age1_wonders", "sul_age2_wonders", "sul_age3_wonders" },
    },
    ["sultanate_ha_tug"] = {
        prefix = "sul_ha_tug_",
        age_type = "landmark",
        in_cardinal = false,
        age_menus = { "sul_ha_tug_age2", "sul_ha_tug_age3", "sul_ha_tug_age4" },
        wonder_menus = { "sul_ha_tug_age1_wonders", "sul_ha_tug_age2_wonders", "sul_ha_tug_age3_wonders" },
    },
    ["templar"] = {
        prefix = "tem_",
        age_type = "upgrade",
        in_cardinal = false,
        age_menus = { "tem_age2", "tem_age3", "tem_age4" },
        wonder_menus = {  },
    },
}

-- Convenience: cardinal.scar-compatible prefix table (all civs)
CONSTRUCTION_MENU_PREFIXES = {
    ["abbasid"] = "abb_",
    ["abbasid_ha_01"] = "abb_ha_01_",
    ["byzantine"] = "byz_",
    ["byzantine_ha_mac"] = "byz_ha_mac_",
    ["chinese"] = "chi_",
    ["chinese_ha_01"] = "chi_ha_01_",
    ["english"] = "eng_",
    ["french"] = "fre_",
    ["french_ha_01"] = "fre_ha_01_",
    ["hre"] = "hre_",
    ["hre_ha_01"] = "hre_ha_01_",
    ["japanese"] = "jpn_",
    ["japanese_ha_sen"] = "jpn_ha_sen_",
    ["lancaster"] = "lan_",
    ["malian"] = "mal_",
    ["mongol"] = "mon_",
    ["mongol_ha_gol"] = "mon_ha_gol_",
    ["ottoman"] = "ott_",
    ["rus"] = "rus_",
    ["sultanate"] = "sul_",
    ["sultanate_ha_tug"] = "sul_ha_tug_",
    ["templar"] = "tem_",
}
